pull_requests:
  do_not_increment_build_number: true

install:
  - cinst gitversion.portable -y

platform: Any CPU

configuration: Release

before_build:
  - nuget restore Source/UsageStats.sln
  - gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: Source/UsageStats.sln
  verbosity: minimal

artifacts:
  - path: Output
    name: UsageStats-$(APPVEYOR_BUILD_VERSION)
    type: zip
